### ISSUE TITLE
Binaries are insecurely downloaded via HTTP

### ISSUE THREAD

**Issue by krisives** [matsjj/thundernetwork#2]
Your website for http://thunder.network doesn't work using any secure connection, it only supports HTTP. This means any binaries downloaded from it can be man-in-the-middle attacked and used to give unsuspecting users malware.

Overall you need to stop linking to HTTP version of the binary, which right now is:

```
http://thunder.network/ThunderWallet.rar
```

The problem is that all traffic to `thunder.network` can be MITM attacked, so they will just serve a fake HTML page with an injected download link.

You should probably get an SSL cert or move the website to a Github repository, host it here on Github, then point your CNAME to that repo.

**Comment by matsjj** [comment]
Thanks for bringing this up. 
Just installed a certificate and redirect from HTTP to HTTPS automatically now.

**Comment by krisives** [comment]
Thanks for the fix!
